<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BUmkRs3' shared service.

return $this->privates['.service_locator.BUmkRs3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'city' => ['privates', '.errored..service_locator.BUmkRs3.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.BUmkRs3": it references class "App\\Entity\\City" but no such service exists.'],
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
], [
    'city' => 'App\\Entity\\City',
    'encoder' => 'App\\Assets\\AppEncoder',
]);
