<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.41jqcnd' shared service.

return $this->privates['.service_locator.41jqcnd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
    'hosting' => ['privates', '.errored..service_locator.41jqcnd.App\\Entity\\Hosting', NULL, 'Cannot autowire service ".service_locator.41jqcnd": it references class "App\\Entity\\Hosting" but no such service exists.'],
], [
    'encoder' => 'App\\Assets\\AppEncoder',
    'hosting' => 'App\\Entity\\Hosting',
]);
