<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JK0XjAA' shared service.

return $this->privates['.service_locator.JK0XjAA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'country' => ['privates', '.errored..service_locator.JK0XjAA.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.JK0XjAA": it references class "App\\Entity\\Country" but no such service exists.'],
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
], [
    'country' => 'App\\Entity\\Country',
    'encoder' => 'App\\Assets\\AppEncoder',
]);
