<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.h.IlB9j' shared service.

return $this->privates['.service_locator.h.IlB9j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
    'hostingRepository' => ['privates', 'App\\Repository\\HostingRepository', 'getHostingRepositoryService.php', true],
], [
    'encoder' => 'App\\Assets\\AppEncoder',
    'hostingRepository' => 'App\\Repository\\HostingRepository',
]);
