<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HlypM3J' shared service.

return $this->privates['.service_locator.HlypM3J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'city' => ['privates', '.errored..service_locator.HlypM3J.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.HlypM3J": it references class "App\\Entity\\City" but no such service exists.'],
    'countryRepository' => ['privates', 'App\\Repository\\CountryRepository', 'getCountryRepositoryService.php', true],
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
], [
    'city' => 'App\\Entity\\City',
    'countryRepository' => 'App\\Repository\\CountryRepository',
    'encoder' => 'App\\Assets\\AppEncoder',
]);
