<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8DzyBBc' shared service.

return $this->privates['.service_locator.8DzyBBc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
    'trip' => ['privates', '.errored..service_locator.8DzyBBc.App\\Entity\\Trip', NULL, 'Cannot autowire service ".service_locator.8DzyBBc": it references class "App\\Entity\\Trip" but no such service exists.'],
], [
    'encoder' => 'App\\Assets\\AppEncoder',
    'trip' => 'App\\Entity\\Trip',
]);
