<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AG75xNx' shared service.

return $this->privates['.service_locator.AG75xNx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
    'tripRepository' => ['privates', 'App\\Repository\\TripRepository', 'getTripRepositoryService.php', true],
], [
    'encoder' => 'App\\Assets\\AppEncoder',
    'tripRepository' => 'App\\Repository\\TripRepository',
]);
