<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Zl7qg3G' shared service.

return $this->privates['.service_locator.Zl7qg3G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
    'validator' => ['privates', 'App\\Assets\\AppValidatorBase64Images', 'getAppValidatorBase64ImagesService.php', true],
], [
    'encoder' => 'App\\Assets\\AppEncoder',
    'validator' => 'App\\Assets\\AppValidatorBase64Images',
]);
