<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.E0XZIiQ' shared service.

return $this->privates['.service_locator.E0XZIiQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'continent' => ['privates', '.errored..service_locator.E0XZIiQ.App\\Entity\\Continent', NULL, 'Cannot autowire service ".service_locator.E0XZIiQ": it references class "App\\Entity\\Continent" but no such service exists.'],
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
], [
    'continent' => 'App\\Entity\\Continent',
    'encoder' => 'App\\Assets\\AppEncoder',
]);
