<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.54Wsr51' shared service.

return $this->privates['.service_locator.54Wsr51'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cityRepository' => ['privates', 'App\\Repository\\CityRepository', 'getCityRepositoryService.php', true],
    'encoder' => ['privates', 'App\\Assets\\AppEncoder', 'getAppEncoderService.php', true],
], [
    'cityRepository' => 'App\\Repository\\CityRepository',
    'encoder' => 'App\\Assets\\AppEncoder',
]);
