<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Assets\AppValidatorBase64Images' shared autowired service.

include_once $this->targetDirs[3].'/src/Assets/AppValidatorBase64Images.php';

return $this->privates['App\\Assets\\AppValidatorBase64Images'] = new \App\Assets\AppValidatorBase64Images();
