<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.NR9L4jU.App\Entity\Activity' shared service.

include_once $this->targetDirs[3].'/src/Entity/Activity.php';

return $this->privates['.errored..service_locator.NR9L4jU.App\\Entity\\Activity'] = new \App\Entity\Activity();
