<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Assets\AppEncoder' shared autowired service.

include_once $this->targetDirs[3].'/src/Assets/AppEncoder.php';

return $this->privates['App\\Assets\\AppEncoder'] = new \App\Assets\AppEncoder();
