<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0EmSvzK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0EmSvzK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0EmSvzK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0EmSvzK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0EmSvzK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0EmSvzK',
    'container.build_id' => '11c78a2f',
    'container.build_time' => 1612896145,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0EmSvzK');
